version: '2.1'
jobs:
  build_main:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.16.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go get ./...
      - run:
          name: go build
          command: go build ./packages/main_app 
  build_second:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.16.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go get ./...
      - run:
          name: Run build
          command: go build ./packages/second_app


workflows:
  version: 2
  build-workflow:
    jobs:
      - build_main
      - build_second
